# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: android

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Changing to Java 8
      run: | 
        javac -version
        sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 8 | cut -d " " -f1) || echo OK
        javac -version
    - name: Install Apache Cordova
      run: sudo npm install -g cordova
    - name: Add Android Platform
      run: cordova platform add android
    - run: npm test
