# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: android

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    strategy:
      matrix:
        platform: [ubuntu-18.04, ubuntu-20.04]
        node-version: [lts/*]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Changing to Java 8
      run: | 
        javac -version
        sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 8 | cut -d " " -f1) || echo OK
        javac -version
    - name: Install Android SDK
      run: |
        sudo apt install android-sdk -y
    - name: Uninstall SDK v31.0.0 and list SDKs
      run: |
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --version
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --uninstall 'build-tools;31.0.0'
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --list
    - name: List SDK dir and mv
      run: |
        ls -la /usr/local/lib/android/sdk/build-tools/
        cd /usr/local/lib/android/sdk/build-tools/32.0.0/
        cp d8 dx && cd lib && cp d8.jar dx.jar
        ls -la /usr/local/lib/android/sdk/build-tools/32.0.0/
    - name: echo PATH
      run: echo "${PATH//:/$'\n'}"
    - name: Install Apache Cordova
      run: npm install -g cordova
    - name: Add Android Platform
      run: | 
        rm -rf platforms/android
        cordova platform add android
    - run: npm test
    - name: Building APK
      run: cordova build android --release
