# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios:
    strategy:
      matrix:
        platform: [macos-latest]
        node-version: [lts/*]
        
    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Changing to Java 8
      run: | 
        javac -version
        export JAVA_HOME=`/usr/libexec/java_home -v 1.8` || echo OK
        javac -version
    - name: Install Apache Cordova
      run: npm install -g cordova
    - name: Add iOS Platform
      run: |
        cordova platform rm android
        cordova platform add ios
    - run: npm test
    - name: Building APP
      run: cordova build ios --release
