# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios:
    strategy:
      matrix:
        platform: [macos-latest]
        node-version: [lts/*]
        
    runs-on: ${{ matrix.platform }}
    
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Installing Java 11
      run: |
        brew update
        brew install java11
    - name: Changing to Java 11
      run: | 
        javac -version
        export JAVA_HOME=`/usr/libexec/java_home -v 1.11` || echo OK
        javac -version
    - name: Install Apache Cordova
      run: npm install -g cordova
    - name: Purge Android and add iOS Platform
      run: |
        cordova platform rm android
        rm -rf platforms/ plugins/
        cordova platform add ios
    - run: npm test
    - run: cordova build ios --release
