# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_HOME: /usr/local/opt/openjdk@11/bin
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  ios:
    strategy:
      matrix:
        platform: [macos-latest]
        node-version: [lts/*]
        
    runs-on: ${{ matrix.platform }}
    
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Installing Java 11
      run: |
        brew update
        brew install java11
        sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
        /usr/libexec/java_home -V
        export JAVA_HOME=`/usr/libexec/java_home -v 11.0`
        javac -version
    - name: Requirements
      run: |
        brew install ios-deploy
        sudo gem install cocoapods
    - name: Install Apache Cordova
      run: npm install -g cordova
    - name: Purge Android and add iOS Platform
      run: |
        cordova platform rm android
        cordova platform rm ios
        rm -rf platforms/ plugins/
        cordova platform add ios
        cordova plugin rm cordova-plugin-network-information
        cordova platform clean ios
    - run: npm test
    - name: Build iOS
      run: cordova build ios --device --buildFlag="CODE_SIGN_IDENTITY=''" --buildFlag="CODE_SIGNING_REQUIRED=NO" --buildFlag="CODE_SIGN_ENTITLEMENTS=''" --buildFlag="CODE_SIGNING_ALLOWED=NO"
